### ISSUE TITLE
Provide host dmd and correctly set HOST_DC on win32 testers

### ISSUE THREAD

**Issue by yebblies** [braddr/d-tester#39]
Currently the build fails like this:
```
HOST_DC=
rename sc.ini _sc.ini
ofmagicport\magicport2.exe magicport\magicport2.d magicport\ast.d  magicport\scanner.d magicport\tokens.d  magicport\parser.d magicport\dprinter.d  magicport\typenames.d magicport\visitor.d  magicport\namer.d
Error: 'ofmagicport\magicport2.exe' not found
```
because HOST_DC is not pointed at a valid dmd.  This blocks ddmd.

I know this isn't new, I'm opening this so I have a good place to nag you about it.

**Comment by kiith-sa** [comment]
Any progresss? This is [blocking DDMD](http://forum.dlang.org/post/m8bt6s$1s86$1@digitalmars.com)

**Comment by braddr** [comment]
A couple days ago I started working on the windows auto-testers again.  Today I finished up enough that both the win_32 and win_64 testers have HOST_DC set.  I'm also setting WIN_HOST_DC to the same binary with a windows/dos formatted path.  Consider this more of a 'what is left to make it work' stage rather than a done stage.  In every liklihood there's more to be done (kind of a given since the testers are still red for both, but for new reasons).

**Comment by yebblies** [comment]
That's fantastic news!  I've updated it to use WIN_HOST_DC.

**Comment by yebblies** [comment]
`WIN_HOST_DC` doesn't seem to be getting passed to make.

**Comment by braddr** [comment]
Oops.. added, though I'm not at all confident that the backslashes 
aren't going to cause some escaping problems.  We'll have to see.

**Comment by yebblies** [comment]
Thanks!  Now time to track down the 64-bit segfault...

**Comment by braddr** [comment]
Closing this one.. at some future date when a more formal form of dependency management is in place this will likely change,  but it's working well enough at the moment.
