### ISSUE TITLE
Hanging tests

### ISSUE THREAD

**Issue by mleise** [braddr/d-tester#50]
Maybe due to quick successive changes of the HEAD commit of the pull request, or some unrelated reason, this test is stuck in the queue since >35 hrs and counting:
https://auto-tester.puremagic.com/show-run.ghtml?projectid=1&runid=2024297&isPull=true

EDIT: I miss a function to peek at the partial build log. It could give a clue as to where it hangs.

**Comment by braddr** [comment]
There doesn't look to be anything wrong with the handling of this pull.

Testing is prioritized based on auto-merge toggled on or not and descending last commit date.  This pull hasn't been set to auto-merge and there's newer commits still being processed.  It's not hanging anywhere other than queue processing speed and waiting for someone to approve the pull for merging.

There's some ui imperfections when it comes to aborted builds, which happens when the master branch has a pull merged into it or when a pull is updated to a newer commit.  But you can see that the that run is marked as deleted and it has a non-zero result code which indicates it's complete.

Additionally, looking at the test history for that pull: 
    https://auto-tester.puremagic.com/pull-history.ghtml?projectid=1&repoid=2&pullid=1541
It shows that lots of activity has happened, including for the same platform, FreeBSD_32, as the test you're looking at.

**Comment by mleise** [comment]
All I was worried about is a stale process burning up server time, when I saw the ever increasing running time of the dmd test marked with R. Paired with the fact that on GitHub there was also exactly one pass missing, I assumed something was hanging. But if you say everything with a 1 next to "deleted" is stopped, deleted and done, I'm relieved.
