### ISSUE TITLE
Old PRs are on the priority queue

### ISSUE THREAD

**Issue by wilzbach** [braddr/d-tester#59]
There are three PRs which are marked as prioritized even though they aren't:

https://auto-tester.puremagic.com/pulls.ghtml?projectid=1

https://github.com/dlang/dmd/pull/7500
https://github.com/dlang/dmd/pull/6831
https://github.com/dlang/dmd/pull/5765

I assume this has something to do with these PRs targeting `stable` before?
Any way we can fix this without needing to bother you?

**Comment by braddr** [comment]
For a little while I was manually bumping the priority of stable requests periodically to see if it helped get them reviewed/approved faster (no real sign of that).  For each of these, them being prioritized is a side effect of that.  When the base branch is changed (in this case from stable to master), that state isn't cleared (and shouldn't be).

A work around would have been to toggle the merge label on and off, but I prefer to be in the loop on problems so that if there's a bug in play it needs to be fixed.

I manually removed the prioritization of these three.
