### ISSUE TITLE
auto-tester gets killed on testing std.regex [Linux hosts]

### ISSUE THREAD

**Issue by wilzbach** [braddr/d-tester#66]
Looks like it's running out of memory?

```
make[1]: *** [generated/linux/release/64/unittest/std/regex/internal/tests.o] Killed
make[1]: *** Waiting for unfinished jobs....
```

https://auto-tester.puremagic.com/show-run.ghtml?projectid=1&runid=2998102&isPull=true

**Comment by braddr** [comment]
It's hard to be sure on associating kernel logs to test cases, but I do see some oom kills of dmd, so possibly.  The host in question there has 4 gigs of memory, which is more than some of the other linux build hosts and less than others.  But if that run failed, then something changed because it's not a new host or new host type... been using the same ec2 instance size for years.

**Comment by braddr** [comment]
resolving this issue.. it's not a tester problem but rather the system under test.
